import type { Metadata } from "next";
// import { Geist, Geist_Mono } from "next/font/google";
import "./globals.css";
import { Toaster } from "@/components/ui/sonner";
import GlobalLayout from "@/components/application/common/GlobalLayout";
import { ThemeProvider } from "@/components/application/common/ThemeProvider";
import GlobalProvider from "@/components/application/common/GlobalProvider";
// const geistSans = Geist({
//   variable: "--font-geist-sans",
//   subsets: ["latin"],
// });

// const geistMono = Geist_Mono({
//   variable: "--font-geist-mono",
//   subsets: ["latin"],
// });

export const metadata: Metadata = {
  title: "Shopizo",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {



  return (
    <html lang="en" suppressHydrationWarning>
      <body
        className={`antialiased`}
      >
        <GlobalProvider>
          <ThemeProvider
            attribute="class"
            defaultTheme="system"
            enableSystem
            disableTransitionOnChange
          >
            <GlobalLayout>
              {children}
              <Toaster position="top-right" richColors />
            </GlobalLayout>
          </ThemeProvider>

        </GlobalProvider>
      </body>
    </html>
  );
}
