import type { Metadata } from "next";
import { Inter } from "next/font/google";
import "./globals.css";
import { Toaster } from "@/components/ui/sonner";
import GlobalLayout from "@/components/application/common/GlobalLayout";
import { ThemeProvider } from "@/components/application/common/ThemeProvider";
import GlobalProvider from "@/components/application/common/GlobalProvider";

const inter = Inter({ subsets: ["latin"] });

export const metadata: Metadata = {
  title: "Shopizo",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  return (
    <html lang="en" className={`${inter.className} antialiased`} suppressHydrationWarning>
      <body>
        <GlobalProvider>
          <ThemeProvider
            attribute="class"
            defaultTheme="system"
            enableSystem
            disableTransitionOnChange
          >
            <GlobalLayout>
              {children}
              <Toaster position="top-right" richColors />
            </GlobalLayout>
          </ThemeProvider>
        </GlobalProvider>
      </body>
    </html>
  );
}
