import type { Metadata } from "next";
// import { Geist, Geist_Mono } from "next/font/google";
import "./globals.css";
import { Toaster } from "@/components/ui/sonner";
import GlobalReduxProvider from "@/components/application/common/GlobalReduxProvider";
import GlobalLayout from "@/components/application/common/GlobalLayout";

// const geistSans = Geist({
//   variable: "--font-geist-sans",
//   subsets: ["latin"],
// });

// const geistMono = Geist_Mono({
//   variable: "--font-geist-mono",
//   subsets: ["latin"],
// });

export const metadata: Metadata = {
  title: "Shopizo",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {



  return (
    <html lang="en">
      <body
        className={`antialiased`}
      >
        <GlobalReduxProvider>
          <GlobalLayout>
            {children}
            <Toaster position="top-right" richColors />
          </GlobalLayout>
        </GlobalReduxProvider>

      </body>
    </html>
  );
}
